local QBCore = exports['qb-core']:GetCoreObject()

if Config.UseBlips then
    CreateThread(function()
        MRRBlip = AddBlipForCoord(LumberDepo.coords)
        SetBlipSprite (MRRBlip, LumberDepo.SetBlipSprite)
        SetBlipDisplay(MRRBlip, LumberDepo.SetBlipDisplay)
        SetBlipScale  (MRRBlip, LumberDepo.SetBlipScale)
        SetBlipAsShortRange(MRRBlip, true)
        SetBlipColour(MRRBlip, LumberDepo.SetBlipColour)
        BeginTextCommandSetBlipName("STRING")
        AddTextComponentSubstringPlayerName(LumberDepo.BlipLabel)
        EndTextCommandSetBlipName(MRRBlip)
        
        PIPBlip = AddBlipForCoord(LumberProcessor.coords)
        SetBlipSprite (PIPBlip, LumberProcessor.SetBlipSprite)
        SetBlipDisplay(PIPBlip, LumberProcessor.SetBlipDisplay)
        SetBlipScale  (PIPBlip, LumberProcessor.SetBlipScale)
        SetBlipAsShortRange(PIPBlip, true)
        SetBlipColour(PIPBlip, LumberProcessor.SetBlipColour)
        BeginTextCommandSetBlipName("STRING")
        AddTextComponentSubstringPlayerName(LumberProcessor.BlipLabel)
        EndTextCommandSetBlipName(PIPBlip)

        PISBlip = AddBlipForCoord(LumberSeller.coords)
        SetBlipSprite (PISBlip, LumberSeller.SetBlipSprite)
        SetBlipDisplay(PISBlip, LumberSeller.SetBlipDisplay)
        SetBlipScale  (PISBlip, LumberSeller.SetBlipScale)
        SetBlipAsShortRange(PISBlip, true)
        SetBlipColour(PISBlip, LumberSeller.SetBlipColour)
        BeginTextCommandSetBlipName("STRING")
        AddTextComponentSubstringPlayerName(LumberSeller.BlipLabel)
        EndTextCommandSetBlipName(PISBlip)

        PIMR = AddBlipForCoord(vector3(-516.4, 5405.45, 73.95))
        SetBlipSprite (PIMR, 79)
        SetBlipDisplay(PIMR, 6)
        SetBlipScale  (PIMR, 0.65)
        SetBlipAsShortRange(PIMR, true)
        SetBlipColour(PIMR, 2)
        BeginTextCommandSetBlipName("STRING")
        AddTextComponentSubstringPlayerName("Tree Field")
        EndTextCommandSetBlipName(PIMR)

        PIMR2 = AddBlipForCoord(vector3(-626.4, 5395.08, 52.16))
        SetBlipSprite (PIMR2, 79)
        SetBlipDisplay(PIMR2, 6)
        SetBlipScale  (PIMR2, 0.65)
        SetBlipAsShortRange(PIMR2, true)
        SetBlipColour(PIMR2, 2)
        BeginTextCommandSetBlipName("STRING")
        AddTextComponentSubstringPlayerName("Tree Field")
        EndTextCommandSetBlipName(PIMR2)

        PIMR3 = AddBlipForCoord(vector3(-645.9, 5275.29, 72.41))
        SetBlipSprite (PIMR3, 79)
        SetBlipDisplay(PIMR3, 6)
        SetBlipScale  (PIMR3, 0.65)
        SetBlipAsShortRange(PIMR3, true)
        SetBlipColour(PIMR3, 2)
        BeginTextCommandSetBlipName("STRING")
        AddTextComponentSubstringPlayerName("Tree Field")
        EndTextCommandSetBlipName(PIMR3)

        PIMR4 = AddBlipForCoord(vector3(-544.46, 5227.5, 75.55))
        SetBlipSprite (PIMR4, 79)
        SetBlipDisplay(PIMR4, 6)
        SetBlipScale  (PIMR4, 0.65)
        SetBlipAsShortRange(PIMR4, true)
        SetBlipColour(PIMR4, 2)
        BeginTextCommandSetBlipName("STRING")
        AddTextComponentSubstringPlayerName("Tree Field")
        EndTextCommandSetBlipName(PIMR4)
    end)
end